#pragma once

#include <opencv2/opencv.hpp>
#include <string>
#include <vector>
#include <numeric>
#include "DroneSimulation.hpp"
#include "PositionEstimation.hpp"
#include "KalmanFilter.hpp"

// Real-world footprint (metres) of each reference crop generated by
// generateReferenceCropsGrid() for the Haifa video pipeline. Shared with
// processVideoNavigation()'s per-frame crop so the two can never silently
// drift out of sync -- they must represent the same ground-sample-distance
// or ORB/SIFT/Hybrid are matching images at two different real-world scales.
constexpr int kReferenceCropMeters = 300;

std::vector<ReferenceCrop> generateReferenceCropsGrid(
    const cv::Mat& map,
    double center_lat, double center_lng,
    int center_x, int center_y,
    double mpp,
    double meters_per_degree_lat,
    double meters_per_degree_lng,
    int grid_spacing_meters = 100,
    int crop_size_meters    = 100
);

/**
 * Process a drone video and estimate position throughout the flight.
 *
 * @param video_frame_gsd  Ground-sample-distance (metres/pixel) of the RAW
 *                      video frame, derived from the altitude/HFOV estimate.
 *                      Used to size the per-frame crop for ORB/SIFT/Hybrid so
 *                      its real-world footprint -- and therefore its scale --
 *                      matches the reference crops', regardless of altitude.
 *                      Unused by the optical-flow path (it self-corrects GSD
 *                      from the affine transform's scale component instead).
 * @param feature_mask  Per-frame feature-detection mask (255=use, 0=exclude).
 *                      Generated by VideoPreprocessor; excludes logos/subtitles.
 *                      Pass an empty Mat to use the default HUD margin mask.
 * @param x_offset      Horizontal pixel offset applied to the ROI crop center.
 * @param y_offset      Vertical pixel offset applied to the ROI crop center.
 * @param frame_times_sec  Optional real capture time (seconds, relative to the
 *                      first frame) indexed by frame_idx. When supplied, the
 *                      Kalman filter's dt comes from real consecutive-frame
 *                      deltas instead of the constant frame_skip/fps -- needed
 *                      for sources like a telemetry-labeled image sequence
 *                      assembled into a synthetic video, where real capture
 *                      intervals vary (e.g. survey-flight turnarounds) instead
 *                      of following a fixed frame rate. Null preserves the
 *                      existing constant-fps behavior exactly.
 */
void processVideoNavigation(
    const std::string& video_path,
    const cv::Mat& reference_map,
    const std::vector<ReferenceCrop>& reference_crops,
    double center_lat, double center_lng,
    int center_x, int center_y,
    double mpp,
    double meters_per_degree_lat,
    double meters_per_degree_lng,
    PositionAlgorithm algorithm,
    const std::string& location_name,
    const std::string& video_name,
    double video_frame_gsd,
    int frame_skip                             = 1,
    std::pair<double, double> initial_position = {0.0, 0.0},
    int start_frame_idx                        = 0,
    int x_offset                               = 0,
    int y_offset                               = 0,
    const cv::Mat& feature_mask                = cv::Mat(),
    const std::vector<double>* frame_times_sec = nullptr
);